apiVersion: batch/v1
kind: Job
metadata:
  name: block-second-app-if-failed
  namespace: second-bgd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: gatekeeper-task
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["exit 1"] 
      restartPolicy: Never
  backoffLimit: 0
