apiVersion: batch/v1
kind: Job
metadata:
  name: bgd-validation-job
  namespace: bgd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    spec:
      containers:
      - name: validation-task
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["exit 1"]
      restartPolicy: Never
  backoffLimit: 2
